#!/bin/bash
# Audio device detection and routing for Docker containers.
#
# Problem: PortAudio/sounddevice mis-reports USB audio device capabilities on
# Jetson (e.g. Jabra shows 0 input channels). This affects both native and
# Docker, but Docker lacks PipeWire/PulseAudio to compensate — the default
# falls to the NVIDIA APE internal card which records noise.
#
# Solution (two tiers):
#   1. PipeWire passthrough — if the host's PipeWire socket is mounted, use
#      the pipewire-alsa plugin to route all audio through it. This gives the
#      container access to the user's system default, including Bluetooth.
#   2. ALSA USB auto-detect — scan arecord/aplay for USB capture devices and
#      generate an .asoundrc that bypasses PortAudio's broken detection.
#
# Audio modes:
#   # Tier 1: PipeWire passthrough (Bluetooth, system default)
#   PULSE_UID=$(id -u) docker compose -f docker-compose.thor.yml up -d
#
#   # Tier 2: ALSA auto-detect (USB devices, no host audio server needed)
#   docker compose -f docker-compose.thor.yml up -d
#
#   # Manual override (any ALSA card name)
#   ALSA_CARD=USB docker compose -f docker-compose.thor.yml up -d

set -e

# ── Tier 1: PipeWire passthrough ──────────────────────────────────────────
# If the host's PipeWire socket is mounted, the pipewire-alsa config
# (99-pipewire-default.conf) routes ALSA through PipeWire automatically.
# We just need to verify the socket is reachable.

try_pipewire_passthrough() {
    # Check common PipeWire socket locations
    local socket
    for socket in /run/user/*/pipewire-0; do
        if [ -S "$socket" ]; then
            echo "Audio: PipeWire passthrough — using host audio server ($socket)"
            return 0
        fi
    done

    # Also check PIPEWIRE_REMOTE env var
    if [ -n "$PIPEWIRE_REMOTE" ] && [ -S "$PIPEWIRE_REMOTE" ]; then
        echo "Audio: PipeWire passthrough — using $PIPEWIRE_REMOTE"
        return 0
    fi

    # Check PulseAudio socket (PipeWire's pulse compat layer)
    if [ -n "$PULSE_SERVER" ]; then
        local socket_path="${PULSE_SERVER#unix:}"
        if [ -S "$socket_path" ]; then
            echo "Audio: PipeWire passthrough via PulseAudio compat ($socket_path)"
            return 0
        fi
    fi

    return 1
}

# ── Tier 2: ALSA USB auto-detect ──────────────────────────────────────────

find_usb_capture_card() {
    # Find card number of first USB device that supports capture.
    # Prefers devices that also support playback (speakerphones).
    local capture_cards playback_cards

    capture_cards=$(arecord -l 2>/dev/null \
        | grep -i 'USB\|usb' \
        | sed -n 's/^card \([0-9]*\):.*/\1/p' \
        | sort -u)

    if [ -z "$capture_cards" ]; then
        return 1
    fi

    playback_cards=$(aplay -l 2>/dev/null \
        | grep -i 'USB\|usb' \
        | sed -n 's/^card \([0-9]*\):.*/\1/p' \
        | sort -u)

    # Prefer a card that has BOTH capture and playback (speakerphone)
    for card in $capture_cards; do
        if echo "$playback_cards" | grep -qx "$card"; then
            echo "$card"
            return 0
        fi
    done

    echo "$capture_cards" | head -1
    return 0
}

get_card_info() {
    local card_num=$1
    local name desc

    # Extract ALSA card name from arecord -l output (works in Docker)
    # Format: "card 2: USB [Jabra SPEAK 410 USB], device 0: USB Audio [USB Audio]"
    name=$(arecord -l 2>/dev/null \
        | grep "^card ${card_num}:" \
        | head -1 \
        | sed 's/card [0-9]*: \([^ ]*\) .*/\1/')

    desc=$(arecord -l 2>/dev/null \
        | grep "^card ${card_num}:" \
        | head -1 \
        | sed 's/card [0-9]*: [^ ]* \[\(.*\)\],.*/\1/')

    echo "${name:-$card_num}|${desc:-unknown}"
}

try_alsa_usb_detect() {
    local card_num card_name card_desc

    if [ -n "$ALSA_CARD" ]; then
        card_name="$ALSA_CARD"
        echo "Audio: using ALSA_CARD=$card_name (user-specified)"
    else
        card_num=$(find_usb_capture_card)
        if [ -z "$card_num" ]; then
            return 1
        fi
        IFS='|' read -r card_name card_desc <<< "$(get_card_info "$card_num")"
        echo "Audio: auto-detected USB device — card $card_num, name=$card_name ($card_desc)"
    fi

    # Generate .asoundrc — overrides the pipewire-alsa default config.
    # Uses card NAME (not number) for reboot stability.
    # Explicit rate/channels on capture helps PortAudio report correct caps.
    cat > /root/.asoundrc << EOF
# Auto-generated by docker-entrypoint.sh — card: ${card_name}
pcm.!default {
    type asym
    capture.pcm "usb_capture"
    playback.pcm "usb_playback"
}

pcm.usb_capture {
    type plug
    slave {
        pcm "hw:${card_name},0"
        rate 16000
        channels 1
    }
}

pcm.usb_playback {
    type plug
    slave {
        pcm "hw:${card_name},0"
    }
}

ctl.!default {
    type hw
    card ${card_name}
}
EOF
    echo "Audio: wrote /root/.asoundrc (card=${card_name}, capture@16kHz mono)"
    return 0
}

# ── Run detection ───────────────────────────────────────────────────────────

if try_pipewire_passthrough; then
    : # Tier 1 — PipeWire handles everything (Bluetooth, system default)
elif try_alsa_usb_detect; then
    : # Tier 2 — direct ALSA to USB device (overrides pipewire-alsa default)
else
    echo "Audio: WARNING — no audio device configured"
    echo "Audio: plug in a USB mic or mount PipeWire socket (PULSE_UID=\$(id -u))"
    # Remove the pipewire-alsa default to prevent connection errors
    rm -f /root/.asoundrc
fi

# ── Start the assistant ───────────────────────────────────────────────────

if [ $# -eq 0 ]; then
    # No arguments — use platform default config (written at build time)
    DEFAULT_CFG=$(cat /app/.default-config 2>/dev/null || echo "configs/thor-sota.yaml")
    echo "Using default config: ${DEFAULT_CFG}"
    exec jetson-assistant assistant --config "$DEFAULT_CFG"
else
    exec jetson-assistant "$@"
fi
